# Generated by Django 3.2 on 2021-04-29 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grid')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('row', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('revealed', models.BooleanField()),
                ('flagged', models.BooleanField()),
                ('value', models.IntegerField()),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grid')),
                ('mine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.mine')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
