# Generated by Django 3.2 on 2021-04-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='clickable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='square',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='square',
            name='revealed',
            field=models.BooleanField(default=False),
        ),
    ]
