# Generated by Django 3.2 on 2021-04-29 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210429_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='square',
            name='mine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mine'),
        ),
    ]
